name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 12am KST
    - cron: '00 15 * * *'
    # Runs every 12 hours
    # - cron: '00 */12 * * *'
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

          # ------ FLAGS ------ #
          # https://github.com/anmol098/waka-readme-stats
          
          # SHOW_OS: 
          #     required: false
          #     description: 'Show the list of OS Worked on In dev metrics'
          #     default: "True"
          SHOW_OS: "True"
          
          # SHOW_PROJECTS:
          #   required: false
          #   description: 'Show the list of projects worked on in dev metrics'
          #   default: "True"
          SHOW_PROJECTS: "True"
          
          # SHOW_EDITORS:
          #   required: false
          #   description: 'Show the Editors used in dev metrics'
          #   default: "True"
          SHOW_EDITORS: "True"
          
          # SHOW_TIMEZONE:
          #   required: false
          #   description: 'Show the time zone in the dev metrics'
          #   default: "True"
          SHOW_TIMEZONE: "False"

          # SHOW_COMMIT:
          #   required: false
          #   description: "Shows the number of commit graph in the dev metrics"
          #   default: "True"
          SHOW_COMMIT: "True"

          # SHOW_LANGUAGE:
          #   required: false
          #   description: "Show the Coding language used in dev metrics"
          #   default: "True"
          SHOW_LANGUAGE: "True"

          # SHOW_LINES_OF_CODE:
          #   required: false
          #   description: "Show the Total Lines of code written Badge till date"
          #   default: "False"
          SHOW_LINES_OF_CODE: "False"

          # SHOW_LANGUAGE_PER_REPO:
          #   required: false
          #   description: "Show language or framework used across different repository"
          #   default: "True"
          SHOW_LANGUAGE_PER_REPO: "False"

          # SHOW_LOC_CHART:
          #   required: false
          #   description: ""
          #   default: "True"
          SHOW_LOC_CHART: "False"

          # SHOW_DAYS_OF_WEEK:
          #   required: false
          #   description: "show day of week you are most productive"
          #   default: "True"
          SHOW_DAYS_OF_WEEK: "False"

          # SHOW_PROFILE_VIEWS:
          #   required: false
          #   description: "Shows the current profile views"
          #   default: "True"
          SHOW_PROFILE_VIEWS: "True"

          # SHOW_SHORT_INFO:
          #   required: false
          #   description: "Shows the short facts"
          #   default: "True"
          SHOW_SHORT_INFO: "True"

          # SHOW_UPDATED_DATE:
          #   required: false
          #   description: "Show updated date"
          #   default: "True"
          SHOW_UPDATED_DATE: "True"

          # SHOW_TOTAL_CODE_TIME:
          #   required: false
          #   description: "Show Total Time you have coded"
          #   default: "True"
          SHOW_TOTAL_CODE_TIME: "False"

          # COMMIT_BY_ME:
          #   required: false
          #   description: "Git commit with your own name and email"
          #   default: "False"
          COMMIT_BY_ME: "False"
          
          # COMMIT_MESSAGE:
          #   required: false
          #   description: "Git commit message"
          #   default: "Updated with Dev Metrics"

          # COMMIT_USERNAME:
          #   required: false
          #   description: "Git commit custom username"
          #   default: ""
          COMMIT_USERNAME: "optimzean"
          
          # COMMIT_EMAIL:
          #   required: false
          #   description: "Git commit custom email"
          #   default: ""
          COMMIT_EMAIL: "optimize.an@gmail.com"

          # COMMIT_SINGLE:
          #   required: false
          #   description: "Erase commit history on each commit"
          #   default: "False"
          COMMIT_SINGLE: "False"

          # LOCALE:
          #   required: false
          #   description: "Show stats in your own language"
          #   default: "en"
          LOCALE: "en"

          # UPDATED_DATE_FORMAT:
          #   required: false
          #   description: "Updated date format"
          #   default: "%d/%m/%Y %H:%M:%S"

          # IGNORED_REPOS:
          #   required: false
          #   description: "Repos you don't want to be counted"
          #   default: ""

          # SYMBOL_VERSION:
          #   required: false
          #   description: "Version of the symbol block and empty of the progress bar"
          #   default: "1"

          # DEBUG_LOGGING:
          #   required: false
          #   description: "Whether to enable action debug logging"
          #   default: ${{ runner.debug }}